# Generated by Django 3.0.8 on 2020-07-21 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f8cabba-b7cb-426c-ac58-8f1f9457a32f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
