# Generated by Django 3.0.8 on 2020-07-21 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200722_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c729a38b-221e-48e2-a8d2-a72de51aae98'), editable=False, primary_key=True, serialize=False),
        ),
    ]
